import {
  DEVBOX_RUNTIMES,
  type DevboxRuntime,
} from "./devbox-constant-runtimes";

export const DEVBOX_DEFAULT_ICON = "https://devbox.bja.sealos.run/logo.svg";

export const DEVBOX_RUNTIME_ICONS: Record<DevboxRuntime, string> = {
  nuxt3: "https://devbox.bja.sealos.run/images/runtime/nuxt3.svg",
  angular: "https://devbox.bja.sealos.run/images/runtime/angular.svg",
  quarkus: "https://devbox.bja.sealos.run/images/runtime/quarkus.svg",
  ubuntu: "https://devbox.bja.sealos.run/images/runtime/ubuntu.svg",
  flask: "https://devbox.bja.sealos.run/images/runtime/flask.svg",
  java: "https://devbox.bja.sealos.run/images/runtime/java.svg",
  chi: "https://devbox.bja.sealos.run/images/runtime/chi.svg",
  net: "https://devbox.bja.sealos.run/images/runtime/net.svg",
  iris: "https://devbox.bja.sealos.run/images/runtime/iris.svg",
  hexo: "https://devbox.bja.sealos.run/images/runtime/hexo.svg",
  python: "https://devbox.bja.sealos.run/images/runtime/python.svg",
  docusaurus: "https://devbox.bja.sealos.run/images/runtime/docusaurus.svg",
  vitepress: "https://devbox.bja.sealos.run/images/runtime/vitepress.svg",
  cpp: "https://devbox.bja.sealos.run/images/runtime/cpp.svg",
  vue: "https://devbox.bja.sealos.run/images/runtime/vue.svg",
  nginx: "https://devbox.bja.sealos.run/images/runtime/nginx.svg",
  rocket: "https://devbox.bja.sealos.run/images/runtime/rocket.svg",
  "debian-ssh": "https://devbox.bja.sealos.run/images/runtime/debian-ssh.svg",
  "vert.x": "https://devbox.bja.sealos.run/images/runtime/vert.x.svg",
  "express.js": "https://devbox.bja.sealos.run/images/runtime/express.js.svg",
  django: "https://devbox.bja.sealos.run/images/runtime/django.svg",
  "next.js": "https://devbox.bja.sealos.run/images/runtime/next.js.svg",
  // sealaf: "https://devbox.bja.sealos.run/images/runtime/laf.svg",
  go: "https://devbox.bja.sealos.run/images/runtime/go.svg",
  react: "https://devbox.bja.sealos.run/images/runtime/react.svg",
  php: "https://devbox.bja.sealos.run/images/runtime/php.svg",
  svelte: "https://devbox.bja.sealos.run/images/runtime/svelte.svg",
  c: "https://devbox.bja.sealos.run/images/runtime/c.svg",
  astro: "https://devbox.bja.sealos.run/images/runtime/astro.svg",
  umi: "https://devbox.bja.sealos.run/images/runtime/umi.svg",
  gin: "https://devbox.bja.sealos.run/images/runtime/gin.svg",
  echo: "https://devbox.bja.sealos.run/images/runtime/echo.svg",
  rust: "https://devbox.bja.sealos.run/images/runtime/rust.svg",
};
