import {
  DEVBOX_RUNTIMES,
  type DevboxRuntime,
} from "./devbox-constant-runtimes";

export const DEVBOX_RUNTIME_ICONS: Record<DevboxRuntime, string> = {
  "C++": "https://devbox.bja.sealos.run/images/runtime/cpp.svg",
  Nuxt3: "https://devbox.bja.sealos.run/images/runtime/nuxt3.svg",
  Hugo: "https://devbox.bja.sealos.run/images/runtime/hugo.svg",
  Laf: "https://devbox.bja.sealos.run/images/runtime/laf.svg",
  Java: "https://devbox.bja.sealos.run/images/runtime/java.svg",
  Chi: "https://devbox.bja.sealos.run/images/runtime/chi.svg",
  PHP: "https://devbox.bja.sealos.run/images/runtime/php.svg",
  Rocket: "https://devbox.bja.sealos.run/images/runtime/rocket.svg",
  Quarkus: "https://devbox.bja.sealos.run/images/runtime/quarkus.svg",
  Debian: "https://devbox.bja.sealos.run/images/runtime/debian.svg",
  Ubuntu: "https://devbox.bja.sealos.run/images/runtime/ubuntu.svg",
  "Spring Boot": "https://devbox.bja.sealos.run/images/runtime/spring-boot.svg",
  Flask: "https://devbox.bja.sealos.run/images/runtime/flask.svg",
  Nginx: "https://devbox.bja.sealos.run/images/runtime/nginx.svg",
  "Vue.js": "https://devbox.bja.sealos.run/images/runtime/vue.svg",
  Python: "https://devbox.bja.sealos.run/images/runtime/python.svg",
  VitePress: "https://devbox.bja.sealos.run/images/runtime/vitepress.svg",
  "Node.js": "https://devbox.bja.sealos.run/images/runtime/node.js.svg",
  Echo: "https://devbox.bja.sealos.run/images/runtime/echo.svg",
  "Next.js": "https://devbox.bja.sealos.run/images/runtime/next.js.svg",
  Angular: "https://devbox.bja.sealos.run/images/runtime/angular.svg",
  React: "https://devbox.bja.sealos.run/images/runtime/react.svg",
  Svelte: "https://devbox.bja.sealos.run/images/runtime/svelte.svg",
  Gin: "https://devbox.bja.sealos.run/images/runtime/gin.svg",
  Rust: "https://devbox.bja.sealos.run/images/runtime/rust.svg",
  UmiJS: "https://devbox.bja.sealos.run/images/runtime/umijs.svg",
  Docusaurus: "https://devbox.bja.sealos.run/images/runtime/docusaurus.svg",
  Hexo: "https://devbox.bja.sealos.run/images/runtime/hexo.svg",
  "Vert.x": "https://devbox.bja.sealos.run/images/runtime/vert.x.svg",
  Go: "https://devbox.bja.sealos.run/images/runtime/go.svg",
  C: "https://devbox.bja.sealos.run/images/runtime/c.svg",
  Iris: "https://devbox.bja.sealos.run/images/runtime/iris.svg",
  Astro: "https://devbox.bja.sealos.run/images/runtime/astro.svg",
  MCP: "https://devbox.bja.sealos.run/images/runtime/mcp.svg",
  Django: "https://devbox.bja.sealos.run/images/runtime/django.svg",
  "Express.js": "https://devbox.bja.sealos.run/images/runtime/express.js.svg",
  ".Net": "https://devbox.bja.sealos.run/images/runtime/net.svg",
};
