import { useEffect, useRef } from "react";
import { v4 as uuidv4 } from "uuid";

// Global in-memory store for triggered effects
const triggeredEffects = new Set<string>();

/**
 * Hook that executes a function once when data becomes ready (not null or undefined)
 * @param data - The data to watch for readiness
 * @param callback - The function to execute when data is ready
 * @param key - Optional unique key for persistence across component lifecycle (auto-generated if not provided)
 */
export const useOnceEffect = <T>(
  data: T | null | undefined,
  callback: (data: T) => void,
  key?: string
) => {
  const hasTriggeredRef = useRef(false);
  const autoGeneratedKeyRef = useRef<string | null>(null);

  useEffect(() => {
    // Generate auto key if none provided
    if (!key && !autoGeneratedKeyRef.current) {
      autoGeneratedKeyRef.current = uuidv4();
    }

    // Use provided key or auto-generated key
    const effectKey = key
      ? `useOnceEffect_${key}`
      : `useOnceEffect_auto_${autoGeneratedKeyRef.current}`;
    const hasTriggeredGlobally = triggeredEffects.has(effectKey);

    if (hasTriggeredRef.current || hasTriggeredGlobally) {
      return;
    }

    // Check if data is ready (not null or undefined) and hasn't been triggered before
    if (data != null) {
      hasTriggeredRef.current = true;
      triggeredEffects.add(effectKey);
      callback(data);
    }
  }, [data, callback, key]);
};

/**
 * Clear all triggered effects (useful for testing or resetting state)
 */
export const clearTriggeredEffects = () => {
  triggeredEffects.clear();
};

/**
 * Remove a specific triggered effect
 */
export const removeTriggeredEffect = (key: string) => {
  triggeredEffects.delete(`useOnceEffect_${key}`);
};
