"use client";

import { useState } from "react";
import type { RuntimeName } from "@/lib/sealos/devbox/schemas/devbox-lifecycle-schema";
import { RuntimeNameSchema } from "@/lib/sealos/devbox/schemas/devbox-lifecycle-schema";
import { Button } from "@/components/ui/button";
import { createDevboxContext } from "@/lib/sealos/devbox/devbox-utils";
import { useCreateDevboxAction } from "@/lib/sealos/devbox/devbox-action/devbox-action";
import { DEVBOX_RUNTIME_ICON_MAP } from "@/lib/sealos/devbox/devbox-constant";
import { useToggle } from "@reactuses/core";

const RUNTIME_OPTIONS = RuntimeNameSchema.options;

export default function AddDevbox() {
  const [selected, setSelected] = useState<RuntimeName>(RUNTIME_OPTIONS[0]);
  const [loading, toggleLoading] = useToggle(false);

  // Create the context and mutation hook
  const devboxContext = createDevboxContext();
  const createDevboxAction = useCreateDevboxAction(devboxContext);

  const handleCreate = () => {
    toggleLoading(true);
    createDevboxAction.mutate(
      {
        runtimeName: selected,
      },
      {
        onSuccess: () => {
          toggleLoading(false);
        },
        onError: (error) => {
          console.error("Failed to create devbox:", error);
          toggleLoading(false);
        },
      }
    );
  };

  return (
    <div className="space-y-4">
      {/* No name input - autogenerated */}
      <div className="flex flex-col gap-2">
        <div className="flex flex-wrap gap-2">
          {RUNTIME_OPTIONS.map((runtime) => (
            <Button
              key={runtime}
              size="sm"
              variant={selected === runtime ? "default" : "outline"}
              onClick={() => setSelected(runtime as RuntimeName)}
              type="button"
              className="flex flex-col items-center justify-center gap-1 w-20 h-20 p-2"
            >
              <img
                src={DEVBOX_RUNTIME_ICON_MAP[runtime]}
                alt={`${runtime} icon`}
                width={32}
                height={32}
                className="mb-1"
              />
              <span className="text-xs text-center break-words">{runtime}</span>
            </Button>
          ))}
        </div>
      </div>
      <Button className="mt-2" onClick={handleCreate} disabled={loading}>
        {loading ? "Creating..." : "Create DevBox"}
      </Button>
    </div>
  );
}
